### ISSUE TITLE
Provide Thrift interface

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#1]
Hi @giuliavezzani 

I think it'd be worth providing a `yarp thrift` rpc interface to this module, which will allow reconstructing superquadrics according to the following two modes:

1. Select a seed point to directly inquiry the result of `lbpExtract` segmentation.
2. Select an object name to query `OPC` and proceed with the subsequent pipeline.

To find out more about `Thrift`, please visit http://www.yarp.it/tutorials.html. Once accustomed with that tutorial, come to my desk; I'll explain you the new way (yet undocumented) of thrifting a yarp module :smile:.

**Comment by pattacini** [comment]
Any progress here? I've seen the thrift interface growing.

**Comment by pattacini** [comment]
@giuliavezzani are you receiving notifications?

**Comment by giuliavezzani** [comment]
Yes, the `thrift rpc interface` has been introduced and tested. [a727bb4](https://github.com/giuliavezzani/superquadric-detection/commit/a727bb4aa800fd40bcccb835ab63dbfb9ec8c335)
