### ISSUE TITLE
Implement spatial density filtering

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#10]
Consider implementing a spatial density filter as this: https://github.com/pattacini/spatial-density-filter.

This filtering can be optionally enabled/disabled via thrift service. Also, its parameters should be accessed via setter/getter methods.

**Comment by giuliavezzani** [comment]
Filtering added. [c5e921d](https://github.com/giuliavezzani/superquadric-detection/commit/c32f6b33c5a7a092f774c3e7423d3fbb5e14b22a)
To be tested.

**Comment by pattacini** [comment]
Uhm, why are you filtering only point clouds loaded from files?
Filtering must be done on all type of point clouds.

Further, you could save one `for-cycle` doing the selection between inlier and outlier already when you call the `FLANN` function.

**Comment by giuliavezzani** [comment]
You're right. I'll modify it.
