### ISSUE TITLE
Conf and scripts

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#12]
- [ ] As of now, you're not installing the application xml script; you should do that as well.
- [ ] Please install also the doc xml.
- [x] The [**`pointCloudFile`**](https://github.com/giuliavezzani/superquadric-detection/blob/master/app/conf/config.ini#L1) key contains relative path to the file. That's wrong, since you should use the [**`yarp::os::ResourceFinder::findFile()`**](http://www.yarp.it/classyarp_1_1os_1_1ResourceFinder.html#aad34b17e2b822611156a63ece477a545) method for that and thus only the file name (i.e. with no path) should be placed in the conf file.

**Comment by giuliavezzani** [comment]
So, I'm supposed to install both the .template ant the .xml?

**Comment by pattacini** [comment]
You ought to install:
- the [xml template](https://github.com/giuliavezzani/superquadric-detection/blob/master/app/script/superquadric-detection.xml.template) via e.g. this [cmake directive](https://github.com/robotology/iol/blob/master/app/CMakeLists.txt#L27).
- the [xml doc](https://github.com/giuliavezzani/superquadric-detection/blob/master/superquadric-detection.xml) via e.g. this [cmake directive](https://github.com/robotology/iol/blob/master/src/iolReachingCalibration/CMakeLists.txt#L30).

**Comment by giuliavezzani** [comment]
Ok, thank you for this information.

**Comment by pattacini** [comment]
[**Here**](https://github.com/giuliavezzani/superquadric-detection/blob/master/CMakeLists.txt#L45-L50) you correctly install scripts and conf as suggested, but then [**this file**](https://github.com/giuliavezzani/superquadric-detection/blob/master/app/CMakeLists.txt) is no longer required, right? :wink:

**Comment by giuliavezzani** [comment]
Ops! I completely forgot it! Thank you!

**Comment by giuliavezzani** [comment]
Removed it. [ def2a93 ](https://github.com/giuliavezzani/superquadric-detection/commit/f86eefe53778a9b46083a675610d2ea13b66d88e)

**Comment by pattacini** [comment]
Uhm... ${PROJECTNAME} is different from ${PROJECT_NAME}

**Comment by giuliavezzani** [comment]
Fixed it. [f86eefe](https://github.com/giuliavezzani/superquadric-detection/commit/05b2be200e147a49de59c52055082f5b3bfcdf52)
