### ISSUE TITLE
Start off using Zenhub Kanban boards

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#13]
Login to https://www.zenhub.io/.

**Comment by giuliavezzani** [comment]
Logged.

**Comment by pattacini** [comment]
Cool :smile: 
So you can use now the kanban board and the relative pipeline, which are integrated within github.

**Comment by pattacini** [comment]
I've already arranged some issues in corresponding pipelines. See https://github.com/giuliavezzani/superquadric-detection/issues#boards.
