### ISSUE TITLE
Wrongly formatted Thrift API documentation

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#14]
Something wrong happened to thrift documentation: http://giuliavezzani.github.io/superquadric-detection/doxygen/doc/html/classsuperquadricDetection__IDL.html.

**Comment by giuliavezzani** [comment]
Fixed it. [f86eefe](https://github.com/giuliavezzani/superquadric-detection/commit/c87037c48f5aa663bc7486eb62709784c03e602a)
