### ISSUE TITLE
Group adavanced parameters, so to be changed only by expert users

### ISSUE THREAD

**Issue by giuliavezzani** [giuliavezzani/superquadric-detection#15]
All the advanced parameters should be grouped in `List`, labelling each parameter with appropriate label.

**Comment by pattacini** [comment]
Rather than simple `List`, you should use `Property`.

**Comment by giuliavezzani** [comment]
Added new advanced parameter thrift service for filter parameters [ 4dc6f72](https://github.com/giuliavezzani/superquadric-detection/commit/554427cf4a1ce234172d8f240c7b300188793066) and improved documentation. [ 359ccb8 ](https://github.com/giuliavezzani/superquadric-detection/commit/6d39fbab07f31720c1cabbf02cce601c191cc3db).
