### ISSUE TITLE
Part based segmentation of superquadrics

### ISSUE THREAD

**Issue by nrj127** [giuliavezzani/superquadric-detection#19]
Hi,

What would be the best approach to do a part-based segmentation of a 3D point cloud. For instance, in case of a cup, how can I segment the handle from the cup and fit two superquadrics.

**Comment by pattacini** [comment]
Hi @nrj127 

**Region growing approach** is a quite effective solution to this problem.
It's described in [Chavalier's article](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.14.3286&rep=rep1&type=pdf).

**Comment by pattacini** [comment]
Closing, feel free to reopen.
