### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#2]
You should provide proper doxygen documentation using the so-called [GitHub Pages](https://pages.github.com/).

**Comment by pattacini** [comment]
Some introductory notes on how we deal with gh-pages branch can be found here: http://wiki.icub.org/wiki/Learning_more_about_git#Using_GitHub_Pages_and_save_space_on_repository.

**Comment by pattacini** [comment]
Any progress here?

**Comment by giuliavezzani** [comment]
Yes, but I'm waiting to arrive at a final version of the code before closing this issue

**Comment by pattacini** [comment]
The xml module containing the documentation should be located one level up.
In fact, it's not about code.

**Comment by giuliavezzani** [comment]
Ok, moved it.
