### ISSUE TITLE
Fill in README.md

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#3]
Take inspiration from e.g. https://github.com/robotology/d4c repository.

The **README.md** should contain:

1. An overview on the theory behind.
2. Instructions on how to build and/or install, along with the list of the required dependencies.
3. Some typical use cases, possibly with code snippets.

**Comment by pattacini** [comment]
@giuliavezzani when you close an issue, try always to write a small description about how you sorted it out. Also, you could provide links to the commit that fixed up the problem.

**Comment by giuliavezzani** [comment]
README.md updated with the required information, [9b45184](https://github.com/giuliavezzani/superquadric-detection/commit/9b45184dd29b33f64099029f5de366e3391447df)
