### ISSUE TITLE
Use appropriate Yarp printing services

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#4]
There are many examples in the code where **`yWarning`** and/or **`yError`** should be clearly used in place of `yInfo`. Please revise in this sense the code.

**Comment by giuliavezzani** [comment]
Done. [22a3bab](https://github.com/giuliavezzani/superquadric-detection/commit/0136e14fb3ffb5fa0917575f2debe0c1428e3051)
