### ISSUE TITLE
Synchronous or asynchronous  

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#5]
The `getPeriod` returns `0.1` seconds, meaning `updateModule` should get called in sync with the internal clock.

However, within `updateModule`, the function `acquirePointsFromBlob` calls a blocking `read`, meaning that you're trying to be in sync with the incoming images (i.e. asynchronously with the internal clock).

There's thus an inconsistency you should address somehow. To be `synchronous` or to be `asynchronous`: what's the best solution and how should you modify your code accordingly?

**Comment by giuliavezzani** [comment]
The `asynchronous` should be the best one. If so, I `getPriod` should return `0.0`.

**Comment by pattacini** [comment]
Perfect! :tada:

**Comment by pattacini** [comment]
You should close fixed issues...

**Comment by giuliavezzani** [comment]
`Asynchronous` solution chosen.  [a727bb4](https://github.com/giuliavezzani/superquadric-detection/commit/a727bb4aa800fd40bcccb835ab63dbfb9ec8c335)
