### ISSUE TITLE
Retrieve superquadric parameters

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#7]
Implement a new thrift service to retrieve the parameters of the superquadric as the outcome of a one-shot detection.

**Comment by giuliavezzani** [comment]
Added. Just to be tested on the robot.

**Comment by giuliavezzani** [comment]
Tested. [189e8a3](https://github.com/giuliavezzani/superquadric-detection/commit/189e8a39ec6ac84de401b0a8034530aea287b302)

**Comment by pattacini** [comment]
Consider detailing the meaning of the 11 parameters returned by the new service.

**Comment by giuliavezzani** [comment]
Added :)

**Comment by pattacini** [comment]
Possibly, it'd be even nicer to have details about the 11 parameters also in the main documentation, which is given in `README.md` file.

**Comment by giuliavezzani** [comment]
Added [ 5a91dd0 ](https://github.com/giuliavezzani/superquadric-detection/commit/c6d9296e5e983ff56f3b2334b50c2c8a96a29fb7).
