### ISSUE TITLE
Request for a service to process point clouds straightaway

### ISSUE THREAD

**Issue by pattacini** [giuliavezzani/superquadric-detection#8]
I really think it could be beneficial to provide a thrift service to process a point cloud per se, by short-cutting the whole vision pipeline.

As result, this service should return the superquadric parameters.

**Comment by pattacini** [comment]
Better than a thrift service would be launching the module with a kind of `offline` mode where the point cloud is passed via command line key.

**Comment by pattacini** [comment]
In this modality, the module should avoid checking the availability of external resources, such as gaze interface...

**Comment by giuliavezzani** [comment]
Added and Tested. [c5e921d](https://github.com/giuliavezzani/superquadric-detection/commit/c32f6b33c5a7a092f774c3e7423d3fbb5e14b22a)
